### PR TITLE
Make lvgl tick more accurate.

### PR DESCRIPTION
**Pull request by rockindy**

### CODE REVIEW

**Review by embeddedt — CHANGES_REQUESTED** [review]
Two suggestions:

* Please rebase on `master` as `dev-6.1` is an old branch.
* Why not just call `lv_tick_inc(delta - one_ms)`?

**Comment by rockindy** [comment]
Hi @embeddedt,

I am still using v6.1, so I am not sure this PR is suitable for latest version. I can rebase this to master branch if you think the latest code needs this PR.

`(delta - one_ms)` is the error we missed before, I add 1ms to `lv_tick_inc()` when the sum of error exceeds 1ms.

**Comment by amirgon** [comment]
> I am still using v6.1

Any plans to move to v7 (or v8 when it's ready)? 
We don't really update the v6 branches any more with new features and fixes, so you are probably missing a few things.

**Comment by rockindy** [comment]
Hi @amirgon,

We may move to v8 later, but no plan for v7.
I have rebase this PR to master #130 .

**Comment by amirgon** [comment]
Closing in favor of #130

**Pull request closed without merging**
