### PR TITLE
fixes empty structures being created

### PR DESCRIPTION
**Pull request by kdschlosser**
The forward declarations has broken things like event callbacks due to structures not being populated with their fields properly This fixes that issue y searching for the forward declarations and their typedefs and making a single object to represent the structure with all the proper fields.

### CODE REVIEW

**Comment by kisvegabor** [comment]
The binding is also updated in `lv_micropython`.

**Comment by kdschlosser** [comment]
OK make sure the fix allows the test to pass on the PR I made to LVGL for the test update,

**Comment by kisvegabor** [comment]
But the CI in lvgl is still failing. 🙁

**Comment by kdschlosser** [comment]
I know, I am working on it. I can't sit that long at the computer.

**Pull request merged**
