### PR TITLE
Port new SDL driver into Micropython Bindings

### PR DESCRIPTION
**Pull request by amirgon**
Port [SDL driver from lv_drivers](https://github.com/lvgl/lv_drivers/tree/master/sdl) into Micropython bindings instead of the existing (old) SDL driver.  
This also adds **keyboard support** and supersedes https://github.com/lvgl/lv_binding_micropython/pull/211 (which seems to be abandoned?)

To run this - need to fix the [Makefile](https://github.com/lvgl/lv_micropython/blob/master/ports/unix/Makefile) on lv_micropython (this will be done after merging this PR):
```diff
diff --git a/ports/unix/Makefile b/ports/unix/Makefile
index a2dbf5af3..b0968bf5f 100644
--- a/ports/unix/Makefile
+++ b/ports/unix/Makefile
@@ -256,8 +256,8 @@ SRC_C += \
        $(wildcard $(VARIANT_DIR)/*.c)
 
 LIB_SRC_C += $(addprefix lib/,\
-    lv_bindings/driver/SDL/SDL_monitor.c \
-    lv_bindings/driver/SDL/SDL_mouse.c \
+    lv_bindings/driver/SDL/sdl_common.c \
+    lv_bindings/driver/SDL/sdl.c \
        lv_bindings/driver/SDL/modSDL.c \
        $(LIB_SRC_C_EXTRA) \
        )
```

@embeddedt - I would appreciate your comments!

- Since I'm basing this on latest SDL LVGL driver, does it by any chance fix https://github.com/lvgl/lv_binding_micropython/issues/97?
- Would keyboard work on the web simulator? How much effort is required to support this?
- Any other comments are very welcome!

### CODE REVIEW

**Comment by embeddedt** [comment]
> Since I'm basing this on latest SDL LVGL driver, does it by any chance fix https://github.com/lvgl/lv_binding_micropython/issues/97?

I've just tested, and unfortunately, it does not. It must be some issue very specific to the threading environment/GC behavior of Micropython? I don't believe Nvidia open-sourced the OpenGL part of their driver stack, which is where the crash happens, so that won't be much help either.

> Would keyboard work on the web simulator? How much effort is required to support this?

This should work out of the box or require very minimal changes. Emscripten supports using the keyboard with SDL so it just needs to be initialized.

**Review by embeddedt — APPROVED** [review]

**Comment by amirgon** [comment]
@embeddedt After merging this and updating lv_micropython, do we expect the simulator to update automatically?
so far, it seems that the new SDL is not available on the simulator:

```python
>>> import SDL
>>> hasattr(SDL, 'keyboard_read')
False
```

**Comment by embeddedt** [comment]
@amirgon Thanks for letting me know, this is fixed now. https://github.com/lvgl/lv_micropython/commit/60e0d6953aa6c2002a32ccabaa0cdc71a52945cb

There was no build failure notification due to a GitHub limitation when merging branches.

**Comment by amirgon** [comment]
> this is fixed now. [lvgl/lv_micropython@60e0d69](https://github.com/lvgl/lv_micropython/commit/60e0d6953aa6c2002a32ccabaa0cdc71a52945cb)

Great! I really missed that js also has its own makefile.  
But I still don't see this on the simulator... Which job is supposed to actually deploy it?

**Comment by embeddedt** [comment]
Can you try clearing your browser cache? I see it here: https://sim.lvgl.io/v8.3/micropython/ports/javascript/index.html

image

**Comment by amirgon** [comment]
> I see it here: https://sim.lvgl.io/v8.3/micropython/ports/javascript/index.html

Aha!  
https://sim.lvgl.io/ only lists versions up to 8.1...  
Perhaps we can have only "latest" v8 version? I don't believe anyone would want to use v8.2 when v8.3 is available.
(but might still want to use v7 or v6)

**Comment by embeddedt** [comment]
@amirgon I'll look into this but it won't be for another week at least.

**Comment by embeddedt** [comment]
The issue turned out to be very simple, unfortunately it took me about two hours to find [these lines](https://github.com/lvgl/lv_binding_micropython/commit/30923af1a185ce27dfdaa46afe29dcfe08325935#diff-da24cd718bcddf9dd6bf3981d58c56d213fbf79e477296f2f5f893615d3137ffL96-L99). :laughing:  I've tested locally and I can type into an LVGL textarea now. The fix should be deployed within 20 minutes or so.

**Comment by amirgon** [comment]
@embeddedt it works great!!
Could you also update the https://sim.lvgl.io/ page?
It has links to v8.0 and v8.1 but not to latest version. I think it's enough to have links to latest version of each major version instead. What do you think?

**Comment by embeddedt** [comment]
Sorry, I forgot to address your previous message. Updated.

**Comment by amirgon** [comment]
Thanks @embeddedt, it's perfect!

**Pull request merged**
