### PR TITLE
Update LVGL and fix binding for multi-instance and parallel rendering architecture changes

### PR DESCRIPTION
**Pull request by PGNetHun**
Fix MicroPython binding to use latest LVGL multi-instance and parallel rendering architecture changes.

Based on [previous lv_conf.h configuration](https://github.com/lvgl/lv_binding_micropython/blob/8053b277cdad75973abb6fab93bb86d71c5897c9/lv_conf.h) and [feat/multi-instance branch](https://github.com/lvgl/lv_binding_micropython/tree/feat/multi-instance), and LVGL's [lv_conf_template.h](https://github.com/lvgl/lvgl/blob/master/lv_conf_template.h) config.

### CODE REVIEW

**Comment by PGNetHun** [comment]
Something still does not work as expected, for example JPEG rendering shows small boxes for some JPEGs:
image
This JPEG is 2x2 subsampled.

Other, not subsampled JPEG image is shown without problem.

**Comment by kisvegabor** [comment]
Thank you! 

Do we really need to target `master` with this change or rather [`feat/parallel-rendering`](https://github.com/lvgl/lv_binding_micropython/tree/feat/parallel-rendering)? Right now we use the `feat/parallel-rendering` branch of this repo with LVGL `master`.


BTW, we are looking for maintainers for the MicroPython binding. I wonder if you would be interested in it. If so I can tell more about the current topics and planned changes. 


> This JPEG is 2x2 subsampled.
Other, not subsampled JPEG image is shown without problem.

The current JPEG decoder is really limited. But if you can send me the original image I can check it out. Maybe it can be easily fixed .

**Comment by PGNetHun** [comment]
> Thank you!
> 
> Do we really need to target `master` with this change or rather [`feat/parallel-rendering`](https://github.com/lvgl/lv_binding_micropython/tree/feat/parallel-rendering)? Right now we use the `feat/parallel-rendering` branch of this repo with LVGL `master`.

I've created a new PR (https://github.com/lvgl/lv_binding_micropython/pull/293), but compared to [feat/multi-instance](https://github.com/lvgl/lv_binding_micropython/tree/feat/multi-instance) , because that contains most recent changes from LVGL.

> BTW, we are looking for maintainers for the MicroPython binding. I wonder if you would be interested in it. If so I can tell more about the current topics and planned changes.

Thank you for the offer, but I'm not (embedded) C developer, I can help only with small changes/bugfixes (when I face issues in my MicroPython hobby project). 
(so I can't tell confidently, that I can (want to) be a maintainer, first I want to update successfully `lv_micropython` repo from `micropython`)

> > This JPEG is 2x2 subsampled.
> > Other, not subsampled JPEG image is shown without problem.
> 
> The current JPEG decoder is really limited. But if you can send me the original image I can check it out. Maybe it can be easily fixed .

Before the parallel rendering changes the same jpeg decoder (TJPGD) has shown this baseline image correctly (with the color format fix mentioned in https://github.com/lvgl/lvgl/pull/4473 ).
I converted (with Paint.NET, see screenshot below) the image to 4:4:4, 4:4:0, 4:2:2, 4:2:0 subsamplings, and only 4:4:4 is shown in MicroPython app fully.
Here are the converted JPEG files: [jpeg-subsampling-tests.zip](https://github.com/lvgl/lv_binding_micropython/files/12717840/jpeg-subsampling-tests.zip)

Convert with Paint.NET ( https://www.getpaint.net/ ):
image

**Comment by PGNetHun** [comment]
I close this PR due to new PR is created to other branch:
https://github.com/lvgl/lv_binding_micropython/pull/293

**Comment by PGNetHun** [comment]
> I've fixed the JPG decoder. All work except "440", but it fails early in the decoder so I believe it wasn't working earlier either.

Thank you, I will test it.
and you are right, I think I have not used any 4:4:0 JPEG images, only 4:2:2 :)

**Pull request closed without merging**
